### PR TITLE
Refactor leaderboard

### PR DESCRIPTION
**Pull request by kuba80-02**

### CODE REVIEW

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Full-screen width looks bad — it's too narrow
image

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
There is an issue with loading the leaderboard, mainly related to resizing:
[Screencast from 13.12.2024 04:49:55.webm](https://github.com/user-attachments/assets/e14338fd-21b3-48a0-b97a-1faa432b589c)

A good example of how the table should load can be load in this [PR](https://github.com/invariant-labs/webapp-eclipse/pull/221) (link: https://webapp-eclipse-rol2v66r4-invariantlabs.vercel.app/liquidity), on the "liquidity" tab:
We want to do the same here:
[Screencast from 13.12.2024 04:58:55.webm](https://github.com/user-attachments/assets/2e24d6bb-8782-4599-aff0-256f4ad9bafd)

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
for a 1450px width or below, the menu disappears:
image

**Comment by Sniezka1927** [comment]
image
The zeros should be trimmed

**Comment by Sniezka1927** [comment]
image
I think it should be `Leaderboard is empty...` y?

**Comment by Sniezka1927** [comment]
image
There's an issue with pagination. When you come back to leaderboard there is a missmatch in indexes for the pagination list and actual positions displayed

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
